# Generated by Django 2.0.6 on 2018-11-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutdent',
            name='email',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
